services:
  api:
    build: ./backend
    
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/code
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - minio

  worker:
    build: ./backend
    command: celery -A celery_app.celery_app worker --loglevel=info
    volumes:
      - ./backend:/code
    env_file:
      - .env
    depends_on:
      - redis
      - minio

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web console

  # docker-compose.yml  (append under services:)
  qdrant:
    image: qdrant/qdrant:v1.9.5
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

volumes:
  minio_data:
  qdrant_storage:

